GET http://localhost:3306/
###
#######################################  /pets-log
GET http://localhost:3306/api/pets-log




################# PETS ROUTES ###########################################
###----------------------------------------GET all
GET http://localhost:3306/api/pets

###---------------------------------------POST pets Table
POST http://localhost:3306/api/pets/table
Content-Type: application/json

###---------------------------------------POST pets 
POST http://localhost:3306/api/pets/row
Content-Type: application/json
###---------------------------------------POST body pets
POST http://localhost:3306/api/pets/row
Content-Type: application/json

 {
    "name": "Miau",
    "dod": "2016-10-11",
    "client_email": "miau@gmail.com"
      }

######

POST http://localhost:3306/api/pets/row/delete/1

################# medications ROUTES ###########################################

GET http://localhost:3306/api/medications
###

POST http://localhost:3306/api/medications/table
Content-Type: application/json

###
POST http://localhost:3306/api/medications/row
Content-Type: application/json

###---------------------------------------------
POST http://localhost:3306/api/medications/row
Content-Type: application/json

 {
    "name": "Mezim",
    "description": "virskinimui"
  }

################### logs routes#########################


GET http://localhost:3306/api/logs
###
POST http://localhost:3306/api/logs/table
Content-Type: application/json
###
POST http://localhost:3306/api/logs/row
Content-Type: application/json

######

POST http://localhost:3306/api/logs/row
Content-Type: application/json

{
    "pet_id": 4,
    "description": "virskinimo sutrikimas",
    "status": "Duoti vaistai, isvyko namo."
  }
